### ISSUE TITLE
Valid e-mail address considered not valid.

### ISSUE THREAD

**Issue by bweston92** [beberlei/assert#111]
`Assertion::email('root@localhost');` throws exception yet is totally valid.

**Comment by beberlei** [comment]
This uses filter_var validate email, nothing we can influence. Also while the email is valid, its a local e-mail, which most validators don't allow because allowing them into a webapp is seldom a good idea.

**Comment by bweston92** [comment]
That's fair enough.

**Comment by grobmeier** [comment]
Could you reopen the issue please, just saying Umlaut emails are not valid. Like info@nähwerk.de

**Comment by bweston92** [comment]
@grobmeier that is a slightly different issue mine was technically invalid (but valid). Your issue is that filter_var I believe doesn't validate UTF-8 email addresses.
