### ISSUE TITLE
Callable message

### ISSUE THREAD

**Issue by maryo** [beberlei/assert#121]
I think it could be useful if it was possible to be able to pass a callable message instead of a string because sometimes the message creation can be time consuming. Is it good or bad idea? What do you think?

**Comment by rquadling** [comment]
Can you give some examples where you would use this?

**Comment by rquadling** [comment]
Please take a look at https://github.com/beberlei/assert#customised-exception-messages.

Hopefully this covers what you are asking for.

**Comment by rquadling** [comment]
No feedback. Closing.
