### ISSUE TITLE
Missing null/isNull assertion

### ISSUE THREAD

**Issue by maryo** [beberlei/assert#124]
Hi. Is there a reason why there is an assertion `notNull` but `isNull`/`null` assertion is missing? I know `same` can be used instead but it is also possible to use `notSame` instead of notNull. Looks like it's not consistent. But I believe there is a reason behind this. Or not?

**Comment by M1ke** [comment]
Could it be because `is_null()` is a direct method in PHP and thus it's not worth the effort of potentially auto-loading a library for a wrapper?

**Comment by dosten** [comment]
:+1: I need the `null` assertion, @rquadling what do you think? I can create a PR.

**Comment by rquadling** [comment]
Create it. I'll review it. Make sure you read the CONTRIBUTING.md. You'll also need to deal with the oddity that will be NullOrNull. But as there is notNull, and by extension NullOrNotNull, I guess we can live with the automatic ones until there's a rewrite.

**Comment by rquadling** [comment]
Once the small change is done, this issue can be closed.
