### ISSUE TITLE
No assertion Assertion#date exists.

### ISSUE THREAD

**Issue by rodrigotavio91** [beberlei/assert#130]
Hi,

I'm trying assert a valid date inside a class, but when I use the method Assertion::date, it throws an exception "No assertion Assertion#date exists." I'm using the "beberlei/assert": "^2.4" in composer.json and using PHP 5.3. 

Do you know if is that because of the Assert's version I'm using?

Many thanks.

**Comment by rquadling** [comment]
It seems as if we need a release. Master has this feature.

**Comment by rquadling** [comment]
Use ``"beberlei/assert": "dev-master",`` instead.

**Comment by rquadling** [comment]
date assertion released, with doc blocks updated for IDE's static analysis.
