### ISSUE TITLE
Assertion::url('http://localhost') not a valid url?

### ISSUE THREAD

**Issue by eriwin** [beberlei/assert#133]
Is this the expected behaviour?

`Assertion::url('http://localhost'); // AssertionFailedException`

In the UrlValidator from the Symfony Validator Component localhost is accepted:
https://github.com/symfony/validator/blob/aee4547e354dca50b470ef2a84a2e2461a3569ba/Tests/Constraints/UrlValidatorTest.php#L82

Support for localhost was added in this PR: https://github.com/symfony/validator/commit/5e60bee8cef4769ba9e2c25c8af354f613a4f7cf

If you want I can do a PR.

**Comment by rquadling** [comment]
Please do a PR. I'll review it and release it as soon as it is ready.

**Comment by rquadling** [comment]
Fixed with https://github.com/beberlei/assert/commit/28fb4f61133f0225558dc490f51cda3f4a430485
