### ISSUE TITLE
Validate Only If

### ISSUE THREAD

**Issue by rochapablo** [beberlei/assert#134]
Is it possible validate the email (for example) only if it is filled?

Like the field is not required, but if populated check if is valid.

I just don't want to do something like:

```
if(!empty($value)) {
   Assert...
}
```

**Comment by M1ke** [comment]
Does using `Assertion::nullOrEmail($value)` work for your use case?

**Comment by rochapablo** [comment]
Unfortunately not because i'm not validating an email field. But now I'm using the "laravel validate".

Thanks anyway.
