### ISSUE TITLE
change boolean to use filter_var instead is_bool

### ISSUE THREAD

**Issue by paulywebster** [beberlei/assert#137]
Hi,

I propose to change the function "boolean" who uses function is_bool by the function filter_var with the filter FILTER_VALIDATE_BOOLEAN who accepts more value than only true or false.

**Comment by stof** [comment]
that would be a different assertion though IMO

**Comment by jdreesen** [comment]
See #89.

**Comment by paulywebster** [comment]
fixed with booleanish assertion
