### ISSUE TITLE
Testing if an array is associative with all keys string

### ISSUE THREAD

**Issue by mirfilip** [beberlei/assert#143]
Hi,
is there a way of testing if an array is associative with all the keys being a (non-empty) string? There are methods like `keyIsset` or `keyExists` but they need `$key`.

**Comment by localheinz** [comment]
@mirfilip 

How about using

```php
Assertion::allIsString(array_keys($data));
```

**Comment by mirfilip** [comment]
@localheinz Awesome, I was feeling I had been missing sth obvious...

Anyway, for true "array that has non empty strings as keys" I'd use lazy assertion chaining:
```
\Assert\lazy()
    ->that($test, 'array')->isArray()
    ->that(array_keys($test), 'keys')->all()->string()
    ->verifyNow();
```
or simply two assertions
```
\Assert\Assertion::isArray($test);
\Assert\Assertion::allIsString(array_keys($test));
```

Thx!
