### ISSUE TITLE
Using assertions in annotations

### ISSUE THREAD

**Issue by iainmckay** [beberlei/assert#144]
We've started using the library in our domain and it's great. We use a lot of transfer objects which have their own validation and tehre is a large overlap, however it is not as extensive as this library. 

Our existing framework for validating transfer objects uses annotations. 

Is there a recommended way to do this?  Would you accept a PR or would it be better suited to a separate project entirely to save on dependencies?

**Comment by stof** [comment]
IMO, this is not in the scope of this library.
Your annotation-based validation system could rely on the assert library internally though, to reuse the assertion.

**Comment by iainmckay** [comment]
Yes, that was my feeling also. Does this functionality exist elsewhere?

**Comment by stof** [comment]
Well, I can tell you about https://github.com/symfony/validator (not based on the assert library), which can be configured through annotations (among other ways).
Zend Framework also has a validator, and probably lots of other frameworks too.

**Comment by iainmckay** [comment]
We use the symfony constraints at the moment but they're not as extensive as this library and we'd like to reuse our custom assertions. Google-ing(?) turned up nothing regarding projects wrapping this one in annotations.

It doesn't seem to be a huge undertaking but we'd rather build on an existing project. We'll look at implementing this ourselves.

Thanks for the responses.
