### ISSUE TITLE
LazyAssertionException does not implement AssertionFailedException interface

### ISSUE THREAD

**Issue by redthor** [beberlei/assert#166]
Thanks for the library!

Is there any reason that `Assert\LazyAssertionException` does not extend `Assert\InvalidArgumentException` and therefore does not implement `Assert\AssertionFailedException`?

It'd be good to catch all exceptions from `\Assert`

**Comment by rquadling** [comment]
Lazy assertion is, in essence, a collection of assertion exceptions.

You can use `\Assert\LazyAssertionException::fromErrors()` to get the assertion errors whilst in a `catch(LazyAssertionException $ex){}`

**Comment by rquadling** [comment]
Having said that, if you want to implement the appropriate interface within `\Assert\LazyAssertionException`, make a pull request and we will review it.

**Comment by redthor** [comment]
There's an option to accomplish what I was after here: https://github.com/beberlei/assert/pull/167

**Comment by rquadling** [comment]
Fixed in the next release.
