### ISSUE TITLE
Add 'between'?

### ISSUE THREAD

**Issue by holtkamp** [beberlei/assert#171]
While writing this:

```php
Assertion::greaterOrEqualThan($weekday, 1);
Assertion::lessOrEqualThan($weekday, 7);
```

made me looking for a ```between``` function:

```php
Assertion::between($weekday, 1, 7);
```

Seems useful... Or has it been considered and purposly not adopted? Would a PR be considered?

**Comment by rquadling** [comment]
Absolutely a PR would be considered.

Please read the [CONTRIBUTING.md](https://github.com/beberlei/assert/blob/master/CONTRIBUTING.md) guide first.

Thank you.

**Comment by localheinz** [comment]
@holtkamp 

Maybe worth considering an argument that allows to exclude the borders?

Or should we have a separate assertion?

```php
Assertion::betweenExclusive($weekday, 0, 8);
```

**Comment by holtkamp** [comment]
@localheinz good one, haven't got time to work on this though 😞

**Comment by holtkamp** [comment]
https://github.com/beberlei/assert/pull/179

"wow, that escalated quickly!" Awesome @localheinz!

**Comment by rquadling** [comment]
Sometimes we don't wait around.
