### ISSUE TITLE
Emailaddress containing exclamation mark considered valid

### ISSUE THREAD

**Issue by holtkamp** [beberlei/assert#200]
After receiving some errors from Amazon SES while trying to deliver an email to ```user!@domain.ext```, I noticed that:

```php
Assertion::email('user!@domain.ext');
```
does not throw any exception. 

I know 
```php
filter_var($value, FILTER_VALIDATE_EMAIL)
``` 
is used internally, which [refers](http://php.net/manual/en/filter.filters.validate.php) to RFC 822. Some Googling brought me here:

http://www.tldp.org/LDP/nag/node189.html

> In the original UUCP environment, the prevalent form was path!host!user, where path described a sequence of hosts the message had to travel before reaching the destination host. This construct is called the bang path notation, because an exclamation mark is loosely called a ``bang''. Today, many UUCP-based networks have adopted RFC-822, and will understand this type of address.

> Now, these two types of addressing don't mix too well. Assume an address of hostA!user@hostB. It is not clear whether the `@' sign takes precedence over the path, or vice versa: do we have to send the message to hostB, which mails it to hostA!user, or should it be sent to hostA, which forwards it to user@hostB?

Not sure I understand this completely, but might it be an idea to also throw an exception on detection of an exclamation mark?

**Comment by rquadling** [comment]
An exclamation mark is, surprisingly, perfectly valid as far as the definition of an email address is concerned. Whether or not an ISP or email provider will allow one is a different story.

As far as the validation is concerned, the code is correct if it says an email address with exclamation mark is present and passes assertion.

Something to keep in mind is that an email address has no guaranteed direct relationship with an account or a recipient. For example, my email is RQuadling@xxxx.com, but I am allowed to say RQuadling+SomeRandomLabel@xxxx.com, or RQuadling+SomeOtherRandomLabel@xxxx.com. I can use the labels to help me identify who is passing my email address around.

The `+` is another perfectly valid character in an email address. But not all websites allow it.

**Comment by rquadling** [comment]
Just so you can see how insane email addresses COULD be ... https://en.wikipedia.org/wiki/Email_address#Examples

**Comment by holtkamp** [comment]
Thanks for the useful explanation, I like the "+SomeRandomLabel" thingie!

Both Google and Amazon SES do not allow the exclamation mark though, will add some "own" validations then 😕

**Comment by rquadling** [comment]
That's the problem. Different providers will support what they want.
