### ISSUE TITLE
Resource and integerish

### ISSUE THREAD

**Issue by manuxi** [beberlei/assert#206]
Please try Assertion::integerish(fopen(__FILE__, 'r')); Works but should not.

**Comment by rquadling** [comment]
Well, PHP's type juggling of a resource to non zero...

`php -r 'var_dump(fopen("./index.php","r"));'` : `resource(5) of type (stream)`
`php -r 'var_dump((int)fopen("./index.php","r"));'` : `int(5)`

So, the resource number is integer-ish ...

Interesting issue. I wonder how many people are asserting that resources are integer-ish and are happy with it.

**Comment by rquadling** [comment]
Thank you for the report. Fixed in https://github.com/beberlei/assert/releases/tag/v2.7.3

**Comment by manuxi** [comment]
Wow, that was fast  ;)
Thank you!
