### ISSUE TITLE
Integerish failing on array

### ISSUE THREAD

**Issue by vaequitas** [beberlei/assert#235]
`Assertion::integerish([])` fails due to Array to String conversion and therefore does not throw the expected exception.

The change from  `\strval(\intval($value)) != \strval($value)` to  `\strval(\intval($value)) !== \strval($value)` in 2.7.7 seems to be causing this issue.

**Comment by rquadling** [comment]
Thank you for reporting this.

A fix is in the works and should be released shortly.
