### ISSUE TITLE
Doubt LazyAssertion

### ISSUE THREAD

**Issue by martinepic** [beberlei/assert#241]
I have an application that has several entities, each entity, has a validation, I need to capture the errors of all entities, how can I proceed?

**Comment by martinepic** [comment]
If in class LazyAssertion has 2 methods: hasErrors(): bool and getErrors(), would help too much.

**Comment by rquadling** [comment]
LazyAssertion::verifyNow() throws an exception with all the errors, so use a try/catch around that and you've got your errors. If LazyAssertion::verifyNow() returns true, then you have no errors.

The assertion library uses true or throws an Exception.
