### ISSUE TITLE
'Array Has At Least One Matching Entry'

### ISSUE THREAD

**Issue by AndyGibsonProtectline** [beberlei/assert#242]
Hi! 

Many apologies if I'm doing something really wrong.

I am trying to use Assert with Behat/MInk and I often end up trying to do something like the following:
Given a parent with these properties
When I add a child with name 'Jo' and age 21
And I view details of the parent
Then I should see a child called 'Jo' aged 21

I then end up looping through a list of details and trying to see if any of the children entries match the given criteria.

I would find it really useful to have an assertion like AtLeastOneValueMatches( array, callback).

Should I...
* shut up, do it myself locally and leave you alone?
* do it myself and offer it as a new Assertion type?
* allow this to be part of something more general (like the previous attempt at 'one*' )?
* ...... ?

Many thanks for a great library :)

**Comment by rquadling** [comment]
You can easily subclass the `\Assert\Assertion` and add your own assertions and/or exception class.

See  https://github.com/beberlei/assert#your-own-assertion-class and https://github.com/beberlei/assert#exception--error-handling.

If you need more help or info, please ask.

For a value checker, `\Assert\Assertion::choice()` or `\Assert\Assertion::inArray()` both exist.

But I think `\Assert\Assertion::satisfy()` may be the assertion you are looking for.

**Comment by AndyGibsonProtectline** [comment]
OK, thank you. I'll do this myself, then.
Thanks for your help!
