### ISSUE TITLE
Integerish - exception message does not match behavior

### ISSUE THREAD

**Issue by ErikRoelofs** [beberlei/assert#243]
When a number fails the assertion for being "Integerish", the message received is:

 Value "%s" is not an integer or a number castable to integer.

However, numbers with padded zeroes (such as "0040") _are_ castable to integers, but _don't_ pass this assertion. I do not know whether this is a problem with the function's behavior, or whether the message could be more accurate, but it was confusing so I want to at least point this out.

**Comment by rquadling** [comment]
The intergerish assertion is misbehaving at the moment. Sorry about that. Looking at trying to get it right today.
