### ISSUE TITLE
When a Count assert fails, it does not explain exactly the issue

### ISSUE THREAD

**Issue by yoannblot** [beberlei/assert#247]
When calling a _Assert::count()_ method, we don't know why it's not equals.

Proposal is to add the calculated count in the message text : 
> List does not contain exactly "6" elements (1 given).

**Comment by rquadling** [comment]
## 2.9.3 - 2018-03-16

### Changes
- Expand error for `\Assert\Assertion::count()` to include the supplied count (Thanks to [Yoann Blot](https://github.com/beberlei/assert/issues/247))
