### ISSUE TITLE
Array with unique items assertion

### ISSUE THREAD

**Issue by koutsoumposval** [beberlei/assert#252]
I have created a custom `uniqueArrayValues` assertion. It asserts that all values of an one dimensional array are unique. Do you think it will be useful in order to create a Pull Request?

**Comment by rquadling** [comment]
Please do.
Please read the https://github.com/beberlei/assert/blob/master/CONTRIBUTING.md.
Please write unit tests!
Apologies for not getting back to you sooner.

**Comment by unkind** [comment]
You also need to clarify case when array contains objects. In my implementation there are two ways: object either implements special `->toHash()` method (similar to Java's one; it's useful for value objects) or "uniqueness" would be checked with "===" operator.
