### ISSUE TITLE
Exception constraints consistency

### ISSUE THREAD

**Issue by pkruithof** [beberlei/assert#254]
I've noticed that not all assertions pass their constraints to the exception, for instance:

`eq` has the expected value passed to the exception:

https://github.com/beberlei/assert/blob/c07fe163d6a3b3e4b1275981ec004397954afa89/lib/Assert/Assertion.php#L305-L313

`greaterThan` on the other hand, has not:

https://github.com/beberlei/assert/blob/c07fe163d6a3b3e4b1275981ec004397954afa89/lib/Assert/Assertion.php#L2074-L2082

I would like to make this consistent across all assertions, in the following manner: 
For every assertion, every argument between the asserted value and the message is part of the `$constraints` array, passed to the exception.

Please let me know if you'd consider this, then I'll make a PR for it.

**Comment by rquadling** [comment]
Happy to accept a PR to make things consistent.
