### ISSUE TITLE
notEq message can be confusing regarding expected value

### ISSUE THREAD

**Issue by rskuipers** [beberlei/assert#258]
First of all, thank you for this library 👍.

I noticed that when using `notEq` I was getting a message which may be consistent with the rest but reads very odd in an error.

```php
Assert::that('foobar')->notEq('foobar');
// Assert\InvalidArgumentException: Value "foobar" is equal to expected value "foobar".
```

When reading this it looks like I'm expecting to get `foobar` as a value, but the opposite is true.
Is this something we should change or is there other reasoning behind this?

I'd be happy to make a PR.

**Comment by rquadling** [comment]
That does look wrong. A PR would be good. If you fancy, review the rest of the messages too.

**Comment by rskuipers** [comment]
@rquadling Will do :+1:
