### ISSUE TITLE
LazyAssertion not open for extension

### ISSUE THREAD

**Issue by DannyvdSluijs** [beberlei/assert#284]
I wanted to extend the LazyAssertion in order to overload the `that` method. As I need to pass some additional details into the exception created by the assertion lib.

With all the properties on the LazyAssertion are private this doesn't allow for easy extending. 

Would you be willing to accept a PR which would change the properties on the LazyAssertion from private too protected? (Like the Assert class already has, which can easily be extended)

**Comment by rquadling** [comment]
Happy to accept a PR. Please make sure you provide an example in a test covering the extension as an example usage. Also please read https://github.com/beberlei/assert/blob/master/CONTRIBUTING.md.

Looking forward to seeing this!

**Comment by DannyvdSluijs** [comment]
PR #285 has been created for this. If you could, at your convenience, have a look and let me know what you think of it. 

I've made sure that:
- The PR uses a feature branch
- Ran `composer assert:cs-fix`
- Didn't add new assertions so no regeneration required.
- Doesn't create new build artefacts
- Travis build is succeeding

**Comment by DannyvdSluijs** [comment]
@rquadling nudging you as a gentle reminder to get your feedback on my PR. Thanks in advance.

**Comment by rquadling** [comment]
Hi. Sorry! Looking.

**Comment by rquadling** [comment]
See the PR for my comments. Please rebase onto master for more uptodate pipeline checks and consistencies.

**Comment by DannyvdSluijs** [comment]
Thanks for the review, I'll pick it up from here.

**Comment by rquadling** [comment]
I've had to release a fix for some BC's. Can you rebase and fix please?

**Comment by DannyvdSluijs** [comment]
@rquadling will do a rebase but still havent found the time to makes changes based your review.

**Comment by DannyvdSluijs** [comment]
Leaving the PR for what it is. Ive no longer need the changes proposed in this PR. If somebody wants to take over feel free.
