### ISSUE TITLE
Latest release breaks BC

### ISSUE THREAD

**Issue by codeliner** [beberlei/assert#287]
Hi,

we have trouble with the 3.2.3 release. It introduced a BC break:

![image](https://user-images.githubusercontent.com/5131987/64564453-dde38d00-d351-11e9-8f98-9ce7b0670adf.png)

We extend `Assertion` to override `Assertion::createException` so that a prooph specific `InvalidArgumentException` is thrown. Please note, prooph's InvalidArgumentException only extends the one from the PHP core and not `\Assert\InvalidArgumentException`, hence we had to override the method and change the way an exception is created:

```php
<?php
/**
 * This file is part of prooph/event-store.
 * (c) 2014-2019 prooph software GmbH <contact@prooph.de>
 * (c) 2015-2019 Sascha-Oliver Prolic <saschaprolic@googlemail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Prooph\EventStore\Util;

use Prooph\EventStore\Exception\InvalidArgumentException;

class Assertion extends \Assert\Assertion
{
    /**
     * Exception to throw when an assertion failed.
     *
     * @var string
     */
    protected static $exceptionClass = InvalidArgumentException::class;

    protected static function createException(
        $value,
        $message,
        $code,
        $propertyPath = null,
        array $constraints = []
    ): InvalidArgumentException {
        $exceptionClass = static::$exceptionClass;

        return new $exceptionClass($message, $code);
    }
}
```

Would you accept a PR that reverts the added type hint to that method? I'm talking about this change: https://github.com/beberlei/assert/commit/dce360b97d4e70c4d90249009ee7f2324940c2f2#diff-4066b84b483f6098378f612ecc64f381R2748

We could release a new version of prooph/event-store that requires latest bebrlei/assert, but this would cause a lot of trouble for our users, b/c they might not be able to upgrade.

Our current require configuration is `"beberlei/assert": "^2.7.1 || ^3.0"`

**Comment by rquadling** [comment]
I'll revert the changes in 3.2 and make a 3.3.0.

I should have been paying more attention to the sig changes as being a BC break.

Sorry about this.

**Comment by codeliner** [comment]
Good news. Thx @rquadling

**Comment by codeliner** [comment]
@rquadling Sorry for the question, but any news on this?
Wouldn't ask if it is a feature request, but our pipeline is still failing due to this BC break. Let me know if I can do anything!

**Comment by rquadling** [comment]
Hopefully fixed in v3.2.4

**Comment by rquadling** [comment]
Well. v3.2.5 ...!

**Comment by codeliner** [comment]
thx @rquadling ! will check it tomorrow on our end.

**Comment by rquadling** [comment]
Thank you.
