### ISSUE TITLE
[BC break] Changes introduced in v3.2.4-v3.2.7 are excluded in v3.3.0

### ISSUE THREAD

**Issue by cvmiert** [beberlei/assert#309]
I ran into the same issue as reported in #288 and realized its fix was dropped in `v3.3.0`.

It looks to me like the `v3` branch never got merged into the main branch while development continued there.

![image](https://user-images.githubusercontent.com/40272863/102420234-f08f4c00-4001-11eb-8173-77ca2af76c9a.png)

**Comment by wilsonge** [comment]
This affects us in @joomla too - I've tried a PR to resolve conflicts here: https://github.com/beberlei/assert/pull/310 - but neds a maintainer to review it as I'm not an expert on this project :(
