### ISSUE TITLE
Assertion::url doesn't respect underscore in domain names

### ISSUE THREAD

**Issue by dzentota** [beberlei/assert#59]
e.g. http://t_rost.rosfirm.ru/ is valid URL, may be it's not corresponds to some specs but it works
replace
`([\pL\pN\pS-]+\.)+[\pL]+`                   # a domain name
with
`([\pL\pN\pS-_]+\.)+[\pL]+`                   # a domain name

**Comment by TrogWarZ** [comment]
Really need it

**Comment by dzentota** [comment]
It is still opened in Symfony https://github.com/symfony/symfony/issues/10467

**Comment by rquadling** [comment]
As you are now able to extend the Assert library and the lack of movement on this issue in Symfony (yes - we are following symfony on this one), I'm closing this issue until as such time Symfony changes it's validation.
