### ISSUE TITLE
How to assert that a value is string or integer?

### ISSUE THREAD

**Issue by sagikazarmark** [beberlei/assert#83]
Numeric is not an option, because it cannot be float.

**Comment by terah** [comment]
Maybe this?
```php
\Assert\that($mVal)->numeric("Must be an int or string")->false(is_float($mVal), "Can't be a float.");
```

**Comment by mdavis1982** [comment]
@terah I don't think that will work... Won't that validate that the value is `numeric` and `false`? I think in this case you'd need to run two separate assertions to make this possible:

```php
try {
    Assert::string($value);
} catch (AssertionFailedException $e) {
    Assert::integer($value);
}
```

**Comment by sagikazarmark** [comment]
@mdavis1982 ended up doing it, thanks.
