### ISSUE TITLE
Make stringify protected

### ISSUE THREAD

**Issue by sagikazarmark** [beberlei/assert#85]
`stringify` method cannot be used in child classes because it is private.

**Comment by mdavis1982** [comment]
Why do you need to subclass the `Assertion` class? I can't think of a valid use case for doing this.

**Comment by sagikazarmark** [comment]
This contradicts with the readme:

https://github.com/beberlei/assert#your-own-assertion-class

The obvious answer: custom assertions.

**Comment by mdavis1982** [comment]
You can still use custom assertions without needing to access the `stringily()` method. I can't see a use case where you need to subclass the `Assertion` class and then access the `stringily()` method. What is the use case for this?

**Comment by sagikazarmark** [comment]
Since this issue is about 6 months old, I don't recall the exact use case. However, I can imagine custom, complex assertion which uses that method. Since the whole Assertion class uses it, I don't think it's hard to find one custom use case. Any case, you want to do something with strings.

**Comment by mdavis1982** [comment]
I think we need to refer this back to @beberlei - but I'm not sure if changing it would have any other implications.

**Comment by beberlei** [comment]
this was done in some PR.
