### ISSUE TITLE
Enhancement: Constants gathering

### ISSUE THREAD

**Issue by RobsenInTheHouse** [beberlei/assert#94]
When checking method parameters i often want to check if it is a correct value of some constants that fit here. So i made a convenience method in my Assert subclass. The source is below, perhaps its useful for you to integrate in some way.

For example you can do:

public class C
{
    const MODE_A = 1;
    const MODE_B = 2;

    const OTHER_XYZ = 'something';

    public functio setMode($mode)
    {
        Assert::that($mode)->inArray(Assert::Constants(__CLASS__, "MODE"));
    }
}

    /**
     * Gather constants having a certain prefix e.g. for validating against them
     *
     * @param mixed $objectOrClassname
     * @param string $prefix
     * @param mixed[] $exclude
     * @return mixed[]
     */
    public static function Constants($objectOrClassname, $prefix, array $exclude = array())
    {
        // Make array from mode constants for easy validation
        $class = new \ReflectionClass($objectOrClassname);
        $found = array();
        foreach ($class->getConstants() as $constName => $constValue)
        {
            if (mb_strpos($constName, $prefix, null) === 0)
            {
                if (!array_search($constValue, $exclude))
                {
                    $found[] = $constValue;
                }
            }
        }
        return $found;
    }

**Comment by mdavis1982** [comment]
Couldn't you achieve the same thing by doing something like:

```php
class Foo
{
    const MODE_A = 1;
    const MODE_B = 2;

    public static $allowedModes = [
        self::MODE_A,
        self::MODE_B
    ];
}
```

And then in your Assertion:

```php
Assert::inArray($mode, Foo::$allowedModes);
```

This seems cleaner in my opinion?

**Comment by beberlei** [comment]
I agree with @mdavis1982
