### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by terah** [beberlei/assert#97]
Hey Benjamin,

I'd like to create very light weight version of the fluent interface to assert for use in some code that is going be very heavily used in my app.  Your license file states that the copyright notice needs to be retained.  So,  would you like the following retained? 

```php
<?php
/**
 * Assert
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to kontakt@beberlei.de so I can send you a copy immediately.
 */
namespace Assert;
/**
 * Assert library
 *
 * @author Benjamin Eberlei <kontakt@beberlei.de>
 *
*/
```

**Comment by beberlei** [comment]
A simple notice about the original code, library name and a link to this repository would suffice.
