### ISSUE TITLE
Arithmetic

### ISSUE THREAD

**Issue by KingCrunch** [beberlei/assert#98]
Currently need to verify the sum of two integers, but I wonder, if something like this (`+`, `*`, `-`, `\`, `%`) fits into the library itself like

```php
\Assert\thatAll([$foo, $bar])->sum(42, 'The sum of foo and bar must be 42');
```

What do you think?

**Comment by mdavis1982** [comment]
I don't think this belongs in the library. If you want to check the sum of two integers, you can do this:

```php
Assert::eq($foo + $bar, $expected);
```
